name: cucm25-coins-dev
services:
  frontend:
    image: ghcr.io/isd-sgcu/cucm25-frontend@sha256:47dc9a3fd6eef9ce46b670c2df94fa98c7da4439535edec6170f869997c9a8de
    ports:
      - "8083:80"
    env_file:
      - ./.env.dev
  backend:
    image: ghcr.io/isd-sgcu/cucm25-backend@sha256:25ba61ffc4ce818faf94caa7cc7bca383d69aee43c25196acb35aac70f1c9474
    restart: always
    depends_on:
      - database
    ports:
      - "8084:8080"
    env_file:
      - ./.env.dev
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend-network
  database:
    image: postgres:17
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge
