name: cucm25-coins-prod
services:
  frontend:
    image: ghcr.io/isd-sgcu/cucm25-frontend:stable
    ports:
      - "8081:80"
    env_file:
      - ./.env.prod
  backend:
    image: ghcr.io/isd-sgcu/cucm25-backend:stable
    restart: always
    depends_on:
      - database
    ports:
      - "8082:8080"
    env_file:
      - ./.env.prod
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend-network
  database:
    image: postgres:17
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge