name: cucm25-coins-dev
services:
  frontend:
    image: ghcr.io/isd-sgcu/cucm25-frontend@sha256:92515aed2f53f9fa8aebc193129b35ceb05945d0c94809cc78b4db7d1469cb31
    ports:
      - "8083:80"
    env_file:
      - ./.env.dev
  backend:
    image: ghcr.io/isd-sgcu/cucm25-backend@sha256:b42a4b5e0e642b50086b282874bed4754fd74804e54103e260ca918ac4473889
    restart: always
    depends_on:
      - database
    ports:
      - "8084:8080"
    env_file:
      - ./.env.dev
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend-network
  database:
    image: postgres:17
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge
